name: Automatic release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Create new release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install git-chglog
        uses: craicoverflow/install-git-chglog@v1

      - name: Generate a release notes
        run: git-chglog -t .chglog/RELEASE.tpl.md -o ${{ github.workspace }}-CHANGELOG.md ${{ github.ref_name}}

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          release_name: Release ${{ github.ref}}
          # body_path: ${{ github.workspace }}-CHANGELOG.md
          prerelease: true
          generate_release_notes: true

  build:
    name: Build binaries for release
    needs: release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: ["386", amd64]
        exclude:
          - goarch: "386"
          - goos: darwin
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build veribi binary
        uses: wangyoucao577/go-release-action@v1.30
        with:
          release_tag: ${{ github.ref_name}}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "1.18"
          binary_name: "veribi"
          build_command: "make build-ci"
          asset_name: "veribi-${{ matrix.goos }}-${{ matrix.goarch }}"
          extra_files: LICENSE
          md5sum: false
