name: Automatic release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Create new release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install git-chglog
        uses: craicoverflow/install-git-chglog@v1

      - name: Generate a release notes
        run: git-chglog -t .chglog/RELEASE.tpl.md -o ${{ github.workspace }}-CHANGELOG.md ${{ github.ref_name}}

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name}}
          release_name: Release ${{ github.ref_name}}
          body_path: ${{ github.workspace }}-CHANGELOG.md
