name: Automatic release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64]
        # exclude:
        #   - goarch: "386"
        #   - goos: darwin
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.18" # The Go version to download (if necessary) and use.

      - name: Build binary ${{ matrix.goos }}/${{ matrix.goarch }}
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: make build-ci

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: artifact_${{ matrix.goos }}_${{ matrix.goarch }}
          path: veribi_${{ matrix.goos }}_${{ matrix.goarch }}.tar.gz

  release:
    name: Create new release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install git-chglog
        uses: craicoverflow/install-git-chglog@v1

      - name: Generate a release notes
        run: git-chglog -t .chglog/RELEASE.tpl.md -o ${{ github.workspace }}-CHANGELOG.md ${{ github.ref_name}}

      - name: Download binaries
        uses: actions/download-artifact@v2

      - name: debug
        run: ls -R

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          release_name: Release ${{ github.ref}}
          body_path: ${{ github.workspace }}-CHANGELOG.md
          files: "*.tar.gz"
          prerelease: true
